version: '3'

services:
  master:
    build: "./images/ros/${ROS_VERSION:-indigo}"
    container_name: master
    command: roscore

  talker:
    build: "./images/ros/${ROS_VERSION:-indigo}"
    container_name: talker
    environment:
      - "ROS_HOSTNAME=talker"
      - "ROS_MASTER_URI=http://master:11311"
    command: rosrun roscpp_tutorials talker

  listener:
    build: "./images/ros/${ROS_VERSION:-indigo}"
    container_name: listener
    environment:
      - "ROS_HOSTNAME=listener"
      - "ROS_MASTER_URI=http://master:11311"
    command: rosrun roscpp_tutorials listener

  gzserver:
    build: "./images/gazebo/gzserver${GAZEBO_VERSION:-8}"
    container_name: gazebo
    environment:
      - "ROS_HOSTNAME=listener"
      - "ROS_MASTER_URI=http://master:11311"
    expose:
      - 11345
    command: gzserver
